# scripts/strapi-write-env-local.ps1
#
# Idempotently write .env.local for the Next.js frontend, copying secrets from
# `/workspace/.env` (Phase 1's secret file) and either leaving Razorpay
# placeholders or merging any keys from -RazorpayFile.
#
# Usage (PowerShell 5.1 on Windows, from repo root):
#   powershell -NoProfile -ExecutionPolicy Bypass -File scripts\strapi-write-env-local.ps1
#   powershell -NoProfile -ExecutionPolicy Bypass -File scripts\strapi-write-env-local.ps1 -RazorpayFile .env.razorpay
#   powershell -NoProfile -ExecutionPolicy Bypass -File scripts\strapi-write-env-local.ps1 -AddOrderToken
#   powershell -NoProfile -ExecutionPolicy Bypass -File scripts\strapi-write-env-local.ps1 -Clean
#
# Required env keys (carried forward from Phase 1):
#   NEXT_PUBLIC_STRAPI_API_URL
#   STRAPI_API_TOKEN
#   NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
#   CLERK_SECRET_KEY
#   NEXT_PUBLIC_CLERK_SIGN_IN_URL
#   NEXT_PUBLIC_CLERK_SIGN_UP_URL
#   E2E_CLERK_USER_EMAIL
#   E2E_CLERK_USER_PASSWORD
#
# Phase 2 keys (added if missing, NOT overwritten):
#   STRAPI_API_TOKEN_WRITE     (place: 1) -RazorpayFile or 2) -AddOrderToken or 3) leave placeholder
#   NEXT_PUBLIC_RAZORPAY_KEY_ID    (Razorpay Test Mode `rzp_test_…`)
#   RAZORPAY_KEY_SECRET
#   RAZORPAY_WEBHOOK_SECRET
#
# This script NEVER overwrites an existing non-empty value. To replace, edit .env.local manually.

[CmdletBinding()]
param(
    [string]$SourceEnv = '.env',
    [string]$RazorpayFile,
    [switch]$AddOrderToken,
    [switch]$Clean
)

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path "$PSScriptRoot\..").Path
$target   = Join-Path $repoRoot '.env.local'
$src      = Join-Path $repoRoot $SourceEnv

if (-not (Test-Path $src)) {
    throw "Source env file not found: $src"
}

if ($Clean -and (Test-Path $target)) {
    Remove-Item $target -Force
}

# Collect keys to copy
$keys = @{
    'NEXT_PUBLIC_STRAPI_API_URL'        = $null
    'STRAPI_API_TOKEN'                  = $null
    'STRAPI_ADMIN_EMAIL'                = $null
    'STRAPI_ADMIN_PASSWORD'             = $null
    'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY' = $null
    'CLERK_SECRET_KEY'                  = $null
    'NEXT_PUBLIC_CLERK_SIGN_IN_URL'     = $null
    'NEXT_PUBLIC_CLERK_SIGN_UP_URL'     = $null
    'E2E_CLERK_USER_EMAIL'              = $null
    'E2E_CLERK_USER_PASSWORD'           = $null
}

function Parse-Env {
    param([string]$Path)
    Get-Content $Path | ForEach-Object {
        if ($_ -match '^\s*#') { return }
        if ($_ -match '^\s*([A-Z0-9_]+)\s*=\s*(.+?)\s*$') {
            return @{ Key = $Matches[1]; Value = $Matches[2] }
        }
    }
}

foreach ($line in (Parse-Env -Path $src)) {
    if ($null -ne $line -and $keys.ContainsKey($line.Key)) {
        $keys[$line.Key] = $line.Value
    }
}

# Backend .env is a fallback for STRAPI_ADMIN_* (not in repo root by default).
$backendEnv = Join-Path $repoRoot 'backend/.env'
if (Test-Path $backendEnv) {
    foreach ($line in (Parse-Env -Path $backendEnv)) {
        if ($null -ne $line -and $keys.ContainsKey($line.Key) -and [string]::IsNullOrEmpty($keys[$line.Key])) {
            $keys[$line.Key] = $line.Value
        }
    }
}

# Read existing .env.local so we can preserve user overrides
$existing = @{}
if (Test-Path $target) {
    foreach ($line in (Parse-Env -Path $target)) {
        if ($null -ne $line) { $existing[$line.Key] = $line.Value }
    }
}

# Razorpay values: read from user-supplied file or use existing values
$razorpayKeys = @('NEXT_PUBLIC_RAZORPAY_KEY_ID', 'RAZORPAY_KEY_SECRET', 'RAZORPAY_WEBHOOK_SECRET')
$razorpay = @{}
if ($RazorpayFile -and (Test-Path (Join-Path $repoRoot $RazorpayFile))) {
    foreach ($line in (Parse-Env -Path (Join-Path $repoRoot $RazorpayFile))) {
        if ($null -ne $line) { $razorpay[$line.Key] = $line.Value }
    }
}

# Order writer token (optional)
$orderToken = if ($AddOrderToken) {
    & "$PSScriptRoot\strapi-issue-order-token.ps1"
    (Select-String -Path $target -Pattern '^STRAPI_API_TOKEN_WRITE=' -ErrorAction SilentlyContinue).Line
} else { $null }

# Compose output
$out = New-Object System.Collections.Generic.List[string]
$out.Add("# Auto-generated by scripts/strapi-write-env-local.ps1 on $(Get-Date -Format o)")
$out.Add("# Edits made here survive unless `-Clean` is used.")
$out.Add("")

function Set-Line {
    param([string]$Key, [string]$Value, [string]$Comment = $null)
    $preferred = if ($existing.ContainsKey($Key) -and $existing[$Key]) { $existing[$Key] } else { $Value }
    if ($Comment) { $out.Add($Comment) }
    $out.Add("$Key=$preferred")
}

Set-Line 'NEXT_PUBLIC_STRAPI_API_URL'        $keys['NEXT_PUBLIC_STRAPI_API_URL']       '# Strapi base URL'
Set-Line 'STRAPI_API_TOKEN'                  $keys['STRAPI_API_TOKEN']                  '# Phase 1 read-only (Product + Category)'
Set-Line 'STRAPI_ADMIN_EMAIL'                $(if ($keys.ContainsKey('STRAPI_ADMIN_EMAIL')) { $keys['STRAPI_ADMIN_EMAIL'] } else { Get-EnvVar -Path (Join-Path $repoRoot 'backend/.env') -Key 'STRAPI_ADMIN_EMAIL' })            '# Strapi admin user (for issuing API tokens)'
Set-Line 'STRAPI_ADMIN_PASSWORD'             $(if ($keys.ContainsKey('STRAPI_ADMIN_PASSWORD')) { $keys['STRAPI_ADMIN_PASSWORD'] } else { Get-EnvVar -Path (Join-Path $repoRoot 'backend/.env') -Key 'STRAPI_ADMIN_PASSWORD' })    '# server-only'
Set-Line 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY' $keys['NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY']
Set-Line 'CLERK_SECRET_KEY'                  $keys['CLERK_SECRET_KEY']
Set-Line 'NEXT_PUBLIC_CLERK_SIGN_IN_URL'     $keys['NEXT_PUBLIC_CLERK_SIGN_IN_URL']
Set-Line 'NEXT_PUBLIC_CLERK_SIGN_UP_URL'     $keys['NEXT_PUBLIC_CLERK_SIGN_UP_URL']
Set-Line 'E2E_CLERK_USER_EMAIL'              $keys['E2E_CLERK_USER_EMAIL']
Set-Line 'E2E_CLERK_USER_PASSWORD'           $keys['E2E_CLERK_USER_PASSWORD']
$out.Add('')
$out.Add('# ----- Phase 2 (mandatory) -----')
Set-Line 'STRAPI_API_TOKEN_WRITE' ($orderToken -replace '^STRAPI_API_TOKEN_WRITE=', '') '# Order writer token (run -AddOrderToken)'
Set-Line 'NEXT_PUBLIC_RAZORPAY_KEY_ID' ($(if ($razorpay.ContainsKey('NEXT_PUBLIC_RAZORPAY_KEY_ID')) { $razorpay['NEXT_PUBLIC_RAZORPAY_KEY_ID'] } else { 'rzp_test_PLACEHOLDER' })) '# Razorpay Test Mode (rzp_test_*)'
Set-Line 'RAZORPAY_KEY_SECRET'        ($(if ($razorpay.ContainsKey('RAZORPAY_KEY_SECRET'))        { $razorpay['RAZORPAY_KEY_SECRET'] }        else { 'PLACEHOLDER' }))
Set-Line 'RAZORPAY_WEBHOOK_SECRET'    ($(if ($razorpay.ContainsKey('RAZORPAY_WEBHOOK_SECRET'))    { $razorpay['RAZORPAY_WEBHOOK_SECRET'] }    else { 'PLACEHOLDER' }))

Set-Content -Path $target -Value $out -Encoding UTF8
Write-Host "Wrote $target ($($out.Count) lines)."
